PASOS GIT 

cd C:\Users\Esperanza\Desktop\UOC\TFM\python
git init
git config user.name 'SpRdgz'
git config user.mail 'esperanzarcf@gmail.com'
git add --all
git commit -m 'primer commit'
git remote add origin https://github.com/SpRdgz/TFM.git
git push -u origin master
git pull
# Fix any merge conflicts, if you have a `README.md` locally
git push -u origin master
cuando pone algo tipo: 
error: failed to push some refs to 'https://github.com/SpRdgz/TFM.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
git pull --allow-unrelated-histories
git push 
SpRdgz
Miguel120887


git config --global core.excludesfile '~/.gitignore'
echo '.ipynb_checkpoints' >> ~/.gitignore
